name: Build Windows Compatible

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Compile with PyInstaller
        run: |
          poetry shell
          poetry build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: compiled-app
          path: dist/
